const TYPES=[{code:'A',name:'限时开挂型',color:'#237f73'},{code:'E',name:'需求终结者',color:'#557db5'},{code:'I',name:'路演气氛组长',color:'#d47a53'},{code:'S',name:'赛博锁匠',color:'#ce667c'},{code:'H',name:'焊点炼金师',color:'#c58c32'},{code:'M',name:'论文炼丹师',color:'#8171bd'}];
const $=s=>document.querySelector(s);
function chart(share){const cx=45,cy=31,R=24,angle=i=>-Math.PI/2+i*Math.PI/3,pt=(i,r)=>[cx+Math.cos(angle(i))*r,cy+Math.sin(angle(i))*r];const grid=[.5,1].map(k=>`<polygon points="${TYPES.map((_,i)=>pt(i,R*k).join(',')).join(' ')}" fill="none" stroke="#f0dce4" stroke-width=".8"/>`).join('');const poly=TYPES.map((t,i)=>pt(i,R*Math.max(.05,share?.[t.code]||0)/100).join(',')).join(' ');return `<svg class="admin-chart" viewBox="0 0 90 64" aria-label="人格雷达图">${grid}<polygon points="${poly}" fill="#e99ab7" fill-opacity=".25" stroke="#d85f8d" stroke-width="1.4"/></svg>`}
function type(code){return TYPES.find(t=>t.code===code)||TYPES[0]}
async function load(){const res=await fetch('/api/admin/results');if(!res.ok)throw new Error('not logged in');const {results}=await res.json();$('#loginPanel').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#recordCount').textContent=`${results.length} 条已提交的学生画像`;$('#recordsBody').innerHTML=results.map(r=>{const t=type(r.primary),date=new Date(r.createdAt).toLocaleString('zh-CN',{dateStyle:'medium',timeStyle:'short'});return `<tr><td>${esc(r.name)}</td><td>${esc(r.major)}</td><td><span style="color:${t.color};font-weight:700">${t.code}</span> · ${t.name}</td><td>${chart(r.share)}</td><td>${date}</td><td><button class="admin-delete" data-delete="${r.id}">删除记录</button></td></tr>`}).join('');$('#emptyState').classList.toggle('hidden',results.length>0);document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('删除这条学生测试记录？此操作无法撤销。'))return;const response=await fetch(`/api/admin/results/${encodeURIComponent(b.dataset.delete)}`,{method:'DELETE'});if(response.ok)load()})}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMessage').textContent='';const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#adminPassword').value})});if(r.ok){$('#adminPassword').value='';await load()}else{const data=await r.json().catch(()=>({}));$('#loginMessage').textContent=data.error||'无法登录，请确认管理员密码已配置。'}});
$('#logoutButton').addEventListener('click',async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()});
load().catch(()=>{});
